### PR TITLE
Add point in time recovery option in backend configuration

### PR DESCRIPTION
**Pull request by mvoitko**

### CODE REVIEW

**Comment by robmorgan** [comment]
Hey @mvoitko,

Thanks for your contribution. How did you test this?

**Comment by mvoitko** [comment]
hey @robmorgan/ I have tested the fix by deploying postgresql db with my fix. When I have done the same without my fix, the option is ignored.

**Comment by robmorgan** [comment]
@mvoitko ok LGTM. I've kicked off the tests in: https://app.circleci.com/pipelines/github/gruntwork-io/terraform-google-sql/91/workflows/6b513bf2-0130-44e9-8ba4-2778b7655466

**Review by robmorgan — DISMISSED** [review]

**Comment by robmorgan** [comment]
**Note:** This might need the updated Google provider in https://github.com/gruntwork-io/terraform-google-sql/pull/51 to work correctly.

**Comment by mvoitko** [comment]
@robmorgan thanks. Will fix the tests to pass on CircleCI and update providers

**Comment by mvoitko** [comment]
@robmorgan Hi, I have updated the PR and rebased the latest master. Could you please review and trigger tests on CI?

**Comment by robmorgan** [comment]
Hi @mvoitko, I'm happy to test your PR, but just scanning the code quickly, it seems you will need to swap your condition statement around. See https://github.com/gruntwork-io/terraform-google-sql/pull/50/files#diff-ae9c8fa94b8488ac9aa4da95f1c19d805e75292969cc372d0925f10e0532640aR79 - I believe this logic would apply to MySQL **instead of** Postgres.

**Comment by mvoitko** [comment]
@robmorgan fixed

**Comment by robmorgan** [comment]
@mvoitko thanks, I plan to release this on Friday.

**Review by robmorgan — APPROVED** [review]
LGTM

**Comment by robmorgan** [comment]
Released in https://github.com/gruntwork-io/terraform-google-sql/releases/tag/v0.3.1

**Pull request merged**
